/*
 * File: app/view/add_admin_win.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.add_admin_win', {
    extend: 'Ext.window.Window',

    height: 220,
    id: 'add_admin_win',
    width: 350,
    layout: {
        type: 'border'
    },
    title: '添加管理员',
    titleAlign: 'center',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'tbspacer',
                            flex: 1
                        },
                        {
                            xtype: 'button',
                            icon: '../img/extjs_icon/accept.gif',
                            text: '确定',
                            listeners: {
                                click: {
                                    fn: me.onButtonClick,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'tbspacer',
                            flex: 1
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'panel',
                    region: 'center',
                    border: false,
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            id: 'lb_add_name',
                            margin: 30,
                            fieldLabel: '管理员名',
                            labelAlign: 'right',
                            labelWidth: 70,
                            allowBlank: false,
                            blankText: '管理员名不能为空',
                            emptyText: '输入管理员名',
                            listeners: {
                                specialkey: {
                                    fn: me.onLb_nameSpecialkey,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'textfield',
                            id: 'lb_add_password',
                            margin: '0 30 0 30',
                            fieldLabel: '管理员密码',
                            labelAlign: 'right',
                            labelWidth: 70,
                            inputType: 'password',
                            allowBlank: false,
                            blankText: '管理员密码不能为空',
                            emptyText: '输入管理员密码',
                            listeners: {
                                specialkey: {
                                    fn: me.onLb_passwordSpecialkey,
                                    scope: me
                                }
                            }
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, eOpts) {
        add_admin_click();
    },

    onLb_nameSpecialkey: function(field, e, eOpts) {
        if (e.getKey() == Ext.EventObject.ENTER) { //响应回车  
            add_admin_click();
        }
    },

    onLb_passwordSpecialkey: function(field, e, eOpts) {
        if (e.getKey() == Ext.EventObject.ENTER) { //响应回车  
            add_admin_click();
        }
    }

});