/*
 * File: app/view/ip_win.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ip_win', {
    extend: 'Ext.window.Window',

    id: 'ip_win',
    width: 400,
    layout: {
        align: 'stretch',
        type: 'vbox'
    },
    closable: false,
    title: '数据库连接设置',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'fieldcontainer',
                    flex: 1,
                    margin: 10,
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            id: 'ip_host',
                            margin: '10 0 0 0',
                            fieldLabel: '主机地址',
                            labelAlign: 'right',
                            labelWidth: 60,
                            allowBlank: false,
                            emptyText: '输入数据库地址'
                        },
                        {
                            xtype: 'textfield',
                            id: 'ip_port',
                            margin: '10 0 0 0',
                            fieldLabel: '端 口',
                            labelAlign: 'right',
                            labelWidth: 60,
                            allowBlank: false,
                            emptyText: '输入数据库端口'
                        },
                        {
                            xtype: 'textfield',
                            id: 'ip_user',
                            margin: '10 0 0 0',
                            fieldLabel: '登录名',
                            labelAlign: 'right',
                            labelWidth: 60,
                            allowBlank: false,
                            emptyText: '输入数据库登录名'
                        },
                        {
                            xtype: 'textfield',
                            id: 'ip_password',
                            margin: '10 0 0 0',
                            fieldLabel: '登录密码',
                            labelAlign: 'right',
                            labelWidth: 60,
                            emptyText: '输入数据库登录密码'
                        },
                        {
                            xtype: 'textfield',
                            id: 'ip_dbname',
                            margin: '10 0 0 0',
                            fieldLabel: '数据库名',
                            labelAlign: 'right',
                            labelWidth: 60,
                            allowBlank: false,
                            emptyText: '输入数据库表名'
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    flex: 1,
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'tbspacer',
                            flex: 1
                        },
                        {
                            xtype: 'button',
                            icon: '../img/extjs_icon/accept.gif',
                            text: '确 定',
                            listeners: {
                                click: {
                                    fn: me.onButtonClick,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'tbspacer',
                            flex: 0.5
                        },
                        {
                            xtype: 'button',
                            icon: '../img/extjs_icon/table_refresh.png',
                            text: '重 置',
                            listeners: {
                                click: {
                                    fn: me.onButtonClick1,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'tbspacer',
                            flex: 0.5
                        },
                        {
                            xtype: 'button',
                            icon: '../img/extjs_icon/rss_go.png',
                            text: '返 回',
                            listeners: {
                                click: {
                                    fn: me.onButtonClick11,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'tbspacer',
                            flex: 1
                        }
                    ]
                }
            ],
            listeners: {
                show: {
                    fn: me.onIp_winShow,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, eOpts) {
        var ip=new IPConfigure();
        ip.setByClient();
    },

    onButtonClick1: function(button, e, eOpts) {
        var ip=new IPConfigure();
        ip.setByServer();
    },

    onButtonClick11: function(button, e, eOpts) {
        Ext.getCmp('ip_win').close();
        Ext.create('MyApp.view.sel_win').show();
    },

    onIp_winShow: function(component, eOpts) {
        var ip=new IPConfigure();
        ip.setByServer();
    }

});