/*
 * File: app/view/main_win.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.main_win', {
    extend: 'Ext.window.Window',

    height: 600,
    width: 800,
    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'tabpanel',
                    region: 'center',
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            border: false,
                            height: 600,
                            width: 800,
                            layout: {
                                type: 'border'
                            },
                            title: '用户管理模块',
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    region: 'center',
                                    margin: '0 5 0 0',
                                    titleAlign: 'center',
                                    forceFit: true,
                                    store: 'user',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            align: 'center',
                                            dataIndex: 'userName',
                                            text: '用户名'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            align: 'center',
                                            dataIndex: 'sex',
                                            text: '性别'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            align: 'center',
                                            dataIndex: 'img',
                                            text: '图像'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            align: 'center',
                                            dataIndex: 'mark',
                                            text: '个性签名'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            align: 'center',
                                            dataIndex: 'email',
                                            text: '注册邮箱'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            align: 'center',
                                            dataIndex: 'regTime',
                                            text: '注册时间'
                                        }
                                    ],
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    icon: '../img/extjs_icon/delete.gif',
                                                    text: '删除'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'pagingtoolbar',
                                            dock: 'bottom',
                                            width: 360,
                                            displayInfo: true,
                                            store: 'user'
                                        }
                                    ]
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'panel',
                                    dock: 'right',
                                    border: false,
                                    layout: {
                                        align: 'stretch',
                                        type: 'vbox'
                                    },
                                    items: [
                                        {
                                            xtype: 'panel',
                                            flex: 1,
                                            border: false,
                                            width: 250,
                                            bodyStyle: {
                                                borderLeft: '1px'
                                            },
                                            title: '按日期删除聊天记录',
                                            titleAlign: 'center',
                                            items: [
                                                {
                                                    xtype: 'datefield',
                                                    margin: '50 0 50 10',
                                                    fieldLabel: '选择日期',
                                                    labelAlign: 'right',
                                                    labelWidth: 60
                                                }
                                            ],
                                            dockedItems: [
                                                {
                                                    xtype: 'toolbar',
                                                    dock: 'bottom',
                                                    border: false,
                                                    items: [
                                                        {
                                                            xtype: 'tbspacer',
                                                            flex: 1
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            icon: '../img/extjs_icon/accept.gif',
                                                            text: '确定'
                                                        },
                                                        {
                                                            xtype: 'tbspacer',
                                                            flex: 1
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'panel',
                                            flex: 1.5,
                                            border: false,
                                            layout: {
                                                type: 'fit'
                                            },
                                            title: '发送系统通知',
                                            titleAlign: 'center',
                                            dockedItems: [
                                                {
                                                    xtype: 'toolbar',
                                                    dock: 'bottom',
                                                    border: false,
                                                    items: [
                                                        {
                                                            xtype: 'tbspacer',
                                                            flex: 1
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            height: 26,
                                                            icon: '../img/extjs_icon/accept.gif',
                                                            text: '发送'
                                                        },
                                                        {
                                                            xtype: 'tbspacer',
                                                            flex: 1
                                                        }
                                                    ]
                                                }
                                            ],
                                            items: [
                                                {
                                                    xtype: 'textareafield',
                                                    margin: 5
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            border: false,
                            height: 600,
                            width: 800,
                            layout: {
                                type: 'border'
                            },
                            title: '管理员模块',
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    region: 'center',
                                    margin: '0 5 0 0',
                                    titleAlign: 'center',
                                    forceFit: true,
                                    store: 'user',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            align: 'center',
                                            dataIndex: 'userName',
                                            text: '用户名'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            align: 'center',
                                            dataIndex: 'img',
                                            text: '权限'
                                        }
                                    ],
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    icon: '../img/extjs_icon/add.gif',
                                                    text: '添加'
                                                },
                                                {
                                                    xtype: 'button',
                                                    icon: '../img/extjs_icon/delete.gif',
                                                    text: '删除'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'pagingtoolbar',
                                            dock: 'bottom',
                                            width: 360,
                                            displayInfo: true,
                                            store: 'user'
                                        }
                                    ]
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'panel',
                                    dock: 'right',
                                    border: false,
                                    layout: {
                                        align: 'stretch',
                                        type: 'vbox'
                                    },
                                    items: [
                                        {
                                            xtype: 'panel',
                                            flex: 1,
                                            border: false,
                                            width: 250,
                                            bodyStyle: {
                                                borderLeft: '1px'
                                            },
                                            title: '密码修改',
                                            titleAlign: 'center',
                                            dockedItems: [
                                                {
                                                    xtype: 'toolbar',
                                                    dock: 'bottom',
                                                    border: false,
                                                    items: [
                                                        {
                                                            xtype: 'tbspacer',
                                                            flex: 1
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            icon: '../img/extjs_icon/accept.gif',
                                                            text: '确定'
                                                        },
                                                        {
                                                            xtype: 'tbspacer',
                                                            flex: 1
                                                        }
                                                    ]
                                                }
                                            ],
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    margin: '40 0 10 0',
                                                    fieldLabel: '原密码',
                                                    labelAlign: 'right',
                                                    labelWidth: 60
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    margin: '20 0 10 0',
                                                    fieldLabel: '新密码',
                                                    labelAlign: 'right',
                                                    labelWidth: 60
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'panel',
                                            flex: 1.5,
                                            border: false,
                                            layout: {
                                                type: 'fit'
                                            },
                                            title: '发送系统通知',
                                            titleAlign: 'center',
                                            dockedItems: [
                                                {
                                                    xtype: 'toolbar',
                                                    dock: 'bottom',
                                                    border: false,
                                                    items: [
                                                        {
                                                            xtype: 'tbspacer',
                                                            flex: 1
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            height: 26,
                                                            icon: '../img/extjs_icon/accept.gif',
                                                            text: '发送'
                                                        },
                                                        {
                                                            xtype: 'tbspacer',
                                                            flex: 1
                                                        }
                                                    ]
                                                }
                                            ],
                                            items: [
                                                {
                                                    xtype: 'textareafield',
                                                    margin: 5
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});